name: winelist
description: Wine list for Luna
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  csv: ^5.0.0
  # google_fonts: ^2.3.2
  http: ^0.13.4
  intl: ^0.17.0

  # 유니코드 이슈 해결 (EUC-KR)
  # https://github.com/jjangga0214/dart-cp949
  # cp949: ^1.2.1
  # NNBD 지원되는 패키지 직접 import

  url_strategy: ^0.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: font
  #     fonts:
  #       - asset: data/font.ttf